# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 23:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('avito_id', models.IntegerField()),
                ('avito_unix_time', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_checked_unixtime', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'item',
                'managed': False,
            },
        ),
    ]
